name: sync user data on merge

on:
  push:
    branches: [ "master" ]
  pull-request:
    branches: [ "master" ]

jobs:
  sync_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create JSON file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.SERVICE_ACCOUNT_JSON_FILE }}